name: Update Date in Markdown

on:
  schedule:
    - cron: "0 17 * * *" 
  workflow_dispatch: 

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update date in README.md
        run: |
              TODAY=$(TZ=Asia/Jakarta date +"%Y-%m-%d")
              sed -i "s/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/$TODAY/" README.md


      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update date to $TODAY" || echo "No changes to commit"
          git push
